project_name: troubleshoot
release:
  github:
    owner: dkoshkin
    name: troubleshoot
builds:
  - id: support-bundle
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/troubleshoot/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/troubleshoot/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -tags containers_image_ostree_stub -tags exclude_graphdriver_devicemapper -tags exclude_graphdriver_btrfs -tags containers_image_openpgp -installsuffix netgo
    binary: support-bundle
    hooks: {}
archives:
  - id: support-bundle
    builds:
      - support-bundle
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: 'support-bundle_{{ .Os }}_{{ .Arch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*